apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: bl0y6oyc2-nodejs 
  janus-idp.io/tekton: bl0y6oyc2-nodejs
  backstage.io/kubernetes-id: bl0y6oyc2-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: bl0y6oyc2-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  