apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: bl0y6oyc2-nodejs-gitops
  description: This is GitOps manifest for bl0y6oyc2-nodejs   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: bl0y6oyc2-nodejs
    janus-idp.io/tekton: bl0y6oyc2-nodejs
    backstage.io/kubernetes-id: bl0y6oyc2-nodejs 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:bl0y6oyc2-nodejs
